### ISSUE TITLE
Cannot read property 'minecraftVersion' of undefined

### ISSUE THREAD

**Issue by james090500** [PrismarineJS/node-minecraft-data#104]
Seem to get this error when using https://github.com/PrismarineJS/node-minecraft-protocol

I don't really have any useful information except its happened 2-3 times? 
Here is the project I am using it in, as you can see nice and simple - https://github.com/MinecraftCapes/minecraftcapes-auth

I have users from all version (1.7.10 - 1.17.1 Forge, Fabric, Vanilla) all joining the proxy.

```
/home/container/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'minecraftVersion' of undefined
    at toMajor (/home/container/node_modules/minecraft-data/index.js:66:27)
    at module.exports (/home/container/node_modules/minecraft-data/index.js:29:24)
    at Client.onHandshake (/home/container/node_modules/minecraft-protocol/src/server/handshake.js:12:36)
    at Object.onceWrapper (node:events:514:26)
    at Client.emit (node:events:394:28)
    at FullPacketParser.<anonymous> (/home/container/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (node:events:394:28)
    at addChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/container/node_modules/readable-stream/lib/_stream_readable.js:241:10)
```

**Comment by rom1504** [comment]
very likely due to @nickelpro commit https://github.com/PrismarineJS/node-minecraft-data/commit/0d271e46d9fa90a17242fb8a18ba20f74bc2c3ef

**Comment by nickelpro** [comment]
We can revert but it will break 1.7 again, not sure I fully understand how this usecase broke

**Comment by nickelpro** [comment]
I think what's happening is someone is connecting with a protocol version that is exclusive to a snapshot release, so our "never return snapshot" policy choice is breaking. What we need to do is _prioritize_ releases over snapshots, but if only snapshots exist return the snapshot

**Comment by rom1504** [comment]
@james090500 could you try to identify one specific version for which you get this error ?

**Comment by james090500** [comment]
Basically any version beneath 1.7.10 (maybe the 1.18 experimental builds as welll...?) But all I have to do is either ping the server, even worse if I try to connect....

![image](https://user-images.githubusercontent.com/20372645/128541008-4cc913ea-ee78-494d-ac23-1b0adef11090.png)

**Comment by james090500** [comment]
**Ok - Please disregard my previous comment! I commented on the wrong issue!**

No, I cannot confirm any versions. The errors has only showed up 5 times and users all over the world log in

**Comment by rom1504** [comment]
probably fixed, do say if you see it again @james090500 (if you have a precise version we can try to reproduce)
